import re

# === Dictionary of translations by locale ===
translations = {
    "en": {
        "crossfadeTitle": "Crossfade",
        "crossfadeEnabledWithDuration": "Crossfade: {ms}ms",
        "@crossfadeEnabledWithDuration": "Autogenerated",
        "gaplessPlaybackEnabled": "Gapless playback (no crossfade)",
        "crossfadeDurationLabel": "Crossfade Duration",
        "crossfadeMinLabel": "0.5s",
        "crossfadeMaxLabel": "10s",
        "crossfadeDescription": "Smoothly fades between tracks. When disabled, gapless playback minimizes gaps without fading."
    },
    "ja": {
        "crossfadeTitle": "クロスフェード",
        "crossfadeEnabledWithDuration": "クロスフェード: {ms}ms",
        "@crossfadeEnabledWithDuration": "Autogenerated",
        "gaplessPlaybackEnabled": "ギャップレス再生（クロスフェードなし）",
        "crossfadeDurationLabel": "クロスフェード時間",
        "crossfadeMinLabel": "0.5秒",
        "crossfadeMaxLabel": "10秒",
        "crossfadeDescription": "トラック間を滑らかにフェードします。無効にするとギャップレス再生が隙間を最小限に抑えます。"
    },
    "zh": {
        "crossfadeTitle": "交叉淡化",
        "crossfadeEnabledWithDuration": "交叉淡化: {ms}ms",
        "@crossfadeEnabledWithDuration": "Autogenerated",
        "gaplessPlaybackEnabled": "无缝播放（无交叉淡化）",
        "crossfadeDurationLabel": "交叉淡化时长",
        "crossfadeMinLabel": "0.5秒",
        "crossfadeMaxLabel": "10秒",
        "crossfadeDescription": "在曲目之间平滑过渡。关闭时，无缝播放最小化间隙。"
    },
    "zh_Hant": {
        "crossfadeTitle": "交叉淡化",
        "crossfadeEnabledWithDuration": "交叉淡化: {ms}ms",
        "@crossfadeEnabledWithDuration": "Autogenerated",
        "gaplessPlaybackEnabled": "無縫播放（無交叉淡化）",
        "crossfadeDurationLabel": "交叉淡化時長",
        "crossfadeMaxLabel": "10秒",
        "crossfadeMinLabel": "0.5秒",
        "crossfadeDescription": "在曲目之間平滑過渡。關閉時，無縫播放最小化間隙。"
    },
    "ru": {
        "crossfadeTitle": "Кроссфейд",
        "crossfadeEnabledWithDuration": "Кроссфейд: {ms}ms",
        "@crossfadeEnabledWithDuration": "Autogenerated",
        "gaplessPlaybackEnabled": "Бесшовное воспроизведение (без кроссфейда)",
        "crossfadeDurationLabel": "Длительность кроссфейда",
        "crossfadeMinLabel": "0.5с",
        "crossfadeMaxLabel": "10с",
        "crossfadeDescription": "Плавный переход между треками. При отключении бесшовное воспроизведение минимизирует паузы."
    }
}

# === Dart implementations (Japanese, Russian, Chinese Simplified) ===
dart_ja = """
  @override
  String get crossfadeTitle => 'クロスフェード';

  @override
  String crossfadeEnabledWithDuration(int ms) {
    if (ms >= 1000) {
      return 'クロスフェード: ${(ms / 1000).toStringAsFixed(1)}s';
    }
    return 'クロスフェード: ${ms}ms';
  }

  @override
  String get gaplessPlaybackEnabled => 'ギャップレス再生（クロスフェードなし）';

  @override
  String get crossfadeDurationLabel => 'クロスフェード時間';

  @override
  String get crossfadeMinLabel => '0.5秒';

  @override
  String get crossfadeMaxLabel => '10秒';

  @override
  String get crossfadeDescription =>
      'トラック間を滑らかにフェードします。無効にするとギャップレス再生が隙間を最小限に抑えます。';
"""

dart_zh = """
  @override
  String get crossfadeTitle => '交叉淡化';

  @override
  String crossfadeEnabledWithDuration(int ms) {
    if (ms >= 1000) {
      return '交叉淡化: ${(ms / 1000).toStringAsFixed(1)}s';
    }
    return '交叉淡化: ${ms}ms';
  }

  @override
  String get gaplessPlaybackEnabled => '无缝播放（无交叉淡化）';

  @override
  String get crossfadeDurationLabel => '交叉淡化时长';

  @override
  String get crossfadeMinLabel => '0.5秒';

  @override
  String get crossfadeMaxLabel => '10秒';

  @override
  String get crossfadeDescription =>
      '在曲目之间平滑过渡。关闭时，无缝播放最小化间隙。';
"""

dart_ru = """
  @override
  String get crossfadeTitle => 'Кроссфейд';

  @override
  String crossfadeEnabledWithDuration(int ms) {
    if (ms >= 1000) {
      return 'Кроссфейд: ${(ms / 1000).toStringAsFixed(1)}s';
    }
    return 'Кроссфейд: ${ms}ms';
  }

  @override
  String get gaplessPlaybackEnabled => 'Бесшовное воспроизведение (без кроссфейда)';

  @override
  String get crossfadeDurationLabel => 'Длительность кроссфейда';

  @override
  String get crossfadeMinLabel => '0.5с';

  @override
  String get crossfadeMaxLabel => '10с';

  @override
  String get crossfadeDescription =>
      'Плавный переход между треками. При отключении бесшовное воспроизведение минимизирует паузы.';
"""


# === Update .arb files ===
for locale, data in translations.items():
    filename = f"lib/l10n/app_{locale}.arb"
    with open(filename, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Build key-value pairs to insert
    insert_lines = []
    for key, value in data.items():
        if key.startswith("@"):
            continue
        insert_lines.append(f'  "{key}": "{value}",')
        meta_key = f"@{key}"
        if meta_key in data:
            # This is autogenerated placeholder metadata
            if "{ms}" in value:
                insert_lines.append(f'  "@{key}": {{ "placeholders": {{ "ms": {{ "type": "int" }} }} }},')
            else:
                insert_lines.append(f'  "@{key}": {{ }},')
    
    insert_str = "\n".join(insert_lines)
    
    # Insert before the last line (which is })
    lines = content.split("\n")
    # Insert before the last line
    last_line = lines[-1]
    # Remove trailing whitespace from second-to-last line and add comma if needed
    penultimate = lines[-2].rstrip()
    if not penultimate.endswith(","):
        lines[-2] = penultimate + ","
    
    # Insert new content before closing brace
    result = "\n".join(lines[:-1]) + "\n" + insert_str + "\n" + lines[-1]
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(result)
    
    print(f"Updated {filename}")


# === Update Dart locale files ===
dart_updates = {
    "app_localizations_ja.dart": dart_ja,
    "app_localizations_zh.dart": dart_zh,
    "app_localizations_ru.dart": dart_ru,
}

# For zh.dart, we need to add Simplified Chinese near line 3369 and Traditional Chinese near line 6734
# Actually, let me check the structure more carefully. The file seems to have two sections.
# Let me read it properly.

# Simpler approach: find "get logEmpty" and insert before the closing "}"
for filename, dart_code in dart_updates.items():
    filepath = f"lib/l10n/{filename}"
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Find the class that has logEmpty
    # First, find the last closing brace of the file
    # The pattern is: the last getter ends with ';' then a newline then '}'
    # Let's find the last occurrence of "String get logEmpty"
    idx = content.rfind("String get logEmpty")
    # Find the end of that line
    end_idx = content.find("\n", idx)
    # Skip to after the semicolon
    semicolon_idx = content.find(";", end_idx)
    if semicolon_idx == -1:
        semicolon_idx = end_idx
    # Now find the closing brace after this
    close_brace_idx = content.find("}", semicolon_idx)
    if close_brace_idx != -1:
        content = content[:close_brace_idx] + dart_code + "\n" + content[close_brace_idx:]
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"Updated {filepath}")

print("\nDone!")
